sudo: false
# Build only master & PRs
branches:
  only:
    - master
    - /^greenkeeper/.*$/

language: node_js

node_js:
  - "6"

script:
  - git diff --name-only --diff-filter=ACM HEAD...$TRAVIS_BRANCH
